#percobaan ke 40

name: Go

on:
  push:
    branches: [ "staging" ]

jobs:
  build: 
    environment: staging
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ vars.DOCKERHUB_USERNAME }}/alfiantobara/library-manager:latest
