name: Go

on:
  push:
    branches: [ "staging" ]

jobs:
  build: 
  environment: staging
    runs-on: ubuntu-latest
    steps:
    - name : Checkout
      uses: actions/checkout@v4

    - name: Connect to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
        
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
      file: ./Dockerfile
        push: true
        tags: ${{ vars.DOCKERHUB_USERNAME }}/alfiantobara/library-manager:latest


