name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive  # Checkout submodules secara rekursif
        
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.20
        
    - name: Build
      run: go build -v ./...
      
    - name: Test
      run: go test -v ./...
